### ISSUE TITLE
Ask Initialize variables

### ISSUE THREAD

**Issue by anjasopo** [dannylee1020/quora-duplicate-questions#1]
I'm studying python with the topic of identifying the same question in quora through the program you created

can you explain this :

_"NB_WORDS_DATA_FILE"_ = 'nb_words.json'
_"MAX_NB_WORDS"_ = 200000
_"MAX_SEQUENCE_LENGTH"_ = 50
_"EMBEDDING_DIM"_ = 300

**Comment by dannylee1020** [comment]
These are just the variables that I declared in the beginning to use throughout the model building process. One can set these values differently to build the model however she wants

**Comment by anjasopo** [comment]
well i understand.
what I want to ask again, how to try to match sentences by entering them manually from the accuracy that has been obtained?
